version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    networks:
      - public
    healthcheck:
      test: ["CMD-SHELL","curl -fsS http://localhost/healthz || exit 1"]
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - private
    healthcheck:
      test: ["CMD-SHELL","curl -fsS http://localhost:5000/healthz || exit 1"]
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - private
    healthcheck:
      test: ["CMD-SHELL","mysqladmin ping -h localhost -p${DB_PASS} || exit 1"]
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - public
      - private
    env_file: .env
    volumes:
      - ./certbot:/var/www/certbot
      - ./letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD-SHELL","curl -fsS http://localhost/healthz || exit 1"]

networks:
  public:
  private:

volumes:
  db_data:
