version: '3.8'
services:
  back:
    build: ./Back
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      - ./Back:/app
    env_file: .env
    ports:
      - "5000:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
  front:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./Front:/app
    command: sh -c "npm ci --legacy-peer-deps && npx ng serve --host 0.0.0.0 --port 4200"
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true

