version: "3.9"
services:
  jenkins:
    build: ./jenkins
    image: cesizen-jenkins:lts-docker
    container_name: cesizen-jenkins
    restart: unless-stopped
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
volumes:
  jenkins_home:

