version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 10
  back:
    build: ./Back
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      - ./Back:/app
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
  front:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./Front:/app
    command: npm start
    ports:
      - "4200:4200"
    environment:
      - API_BASE_URL=http://localhost:5000
volumes:
  db_data:
